# Generated by Django 3.1.3 on 2021-06-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='car_name', max_length=200)),
                ('description', models.CharField(default='Description', max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='car_name', max_length=200)),
                ('dealer', models.IntegerField(null=True)),
                ('model', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('wagon', 'Wagon'), ('hyper', 'Hyper')], default='sedan', max_length=20)),
                ('year', models.DateField()),
                ('car_make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
