# Generated by Django 3.1.3 on 2021-06-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20210609_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='model',
            new_name='car_type',
        ),
    ]
